version: 2.1

jobs:
  lint:
    docker:
      - image: circleci/node:fermium
    steps:
      - checkout
      - run: yarn
      - run: yarn lint


workflows:
  version: 2
  check-style:
    jobs:
      - lint:
          filters:
            branches:
              only:
                - main
